# Generated by Django 5.2.4 on 2025-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique_for_date='created_at'),
        ),
    ]
