# Generated by Django 5.2.4 on 2025-08-06 09:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
